// SPDX-License-Identifier: Apache-2.0

package mprbackend

import (
	"fmt"
	"strings"

	"github.com/mendixlabs/mxcli/modelsdk/element"
	genJA "github.com/mendixlabs/mxcli/modelsdk/gen/javaactions"
)

// generateJavaSourceGen renders the Java source for a Java action,
// reading parameter and return-type information from gen-typed elements
// directly. Output is byte-identical to the legacy
// sdk/mpr.generateJavaSource (Stage 3.3.2.E1 retired the bridge that
// converted gen→sdk before calling that legacy function).
//
// The polymorphic Java type lookup is keyed on the canonical
// CodeActions$X namespace; older MPRs may store JavaActions$X for the
// same shape (per the schema gap documented in
// cmd_javaactions_gen.go), so both prefixes are accepted.
func generateJavaSourceGen(moduleName, actionName string, userCode string, params []*genJA.JavaActionParameter, returnType element.Element, extraImports []string, extraCode string) string {
	moduleNameLower := strings.ToLower(moduleName)

	returnTypeStr, returnTypeSimple := getJavaReturnTypeGen(returnType)

	var sb strings.Builder

	sb.WriteString("// This file was generated by Mendix Studio Pro.\n")
	sb.WriteString("//\n")
	sb.WriteString("// WARNING: Only the following code will be retained when actions are regenerated:\n")
	sb.WriteString("// - the import list\n")
	sb.WriteString("// - the code between BEGIN USER CODE and END USER CODE\n")
	sb.WriteString("// - the code between BEGIN EXTRA CODE and END EXTRA CODE\n")
	sb.WriteString("// Other code you write will be lost the next time you deploy the project.\n")
	sb.WriteString("// Special characters, e.g., é, ö, à, etc. are supported in comments.\n\n")

	sb.WriteString(fmt.Sprintf("package %s.actions;\n\n", moduleNameLower))

	sb.WriteString("import com.mendix.systemwideinterfaces.core.IContext;\n")
	sb.WriteString("import com.mendix.systemwideinterfaces.core.UserAction;\n")
	for _, imp := range extraImports {
		sb.WriteString(imp)
		sb.WriteString("\n")
	}
	sb.WriteString("\n")

	sb.WriteString(fmt.Sprintf("public class %s extends UserAction<%s>\n", actionName, returnTypeStr))
	sb.WriteString("{\n")

	for _, param := range params {
		if param == nil {
			continue
		}
		javaType := getJavaParamTypeGen(param.ActionParameterType())
		sb.WriteString(fmt.Sprintf("\tprivate final %s %s;\n", javaType, param.Name()))
	}
	sb.WriteString("\n")

	sb.WriteString(fmt.Sprintf("\tpublic %s(\n", actionName))
	sb.WriteString("\t\tIContext context")
	for _, param := range params {
		if param == nil || param.Name() == "" {
			continue
		}
		javaType := getJavaParamTypeGen(param.ActionParameterType())
		name := param.Name()
		sb.WriteString(fmt.Sprintf(",\n\t\t%s _%s", javaType, strings.ToLower(name[:1])+name[1:]))
	}
	sb.WriteString("\n\t)\n")
	sb.WriteString("\t{\n")
	sb.WriteString("\t\tsuper(context);\n")
	for _, param := range params {
		if param == nil || param.Name() == "" {
			continue
		}
		name := param.Name()
		paramLower := strings.ToLower(name[:1]) + name[1:]
		sb.WriteString(fmt.Sprintf("\t\tthis.%s = _%s;\n", name, paramLower))
	}
	sb.WriteString("\t}\n\n")

	sb.WriteString("\t@java.lang.Override\n")
	sb.WriteString(fmt.Sprintf("\tpublic %s executeAction() throws Exception\n", returnTypeStr))
	sb.WriteString("\t{\n")
	sb.WriteString("\t\t// BEGIN USER CODE\n")
	sb.WriteString("\n")

	for line := range strings.SplitSeq(userCode, "\n") {
		sb.WriteString("\t\t")
		sb.WriteString(line)
		sb.WriteString("\n")
	}

	sb.WriteString("\n")
	sb.WriteString("\t\t// END USER CODE\n")
	sb.WriteString("\t}\n\n")

	sb.WriteString("\t/**\n")
	sb.WriteString("\t * Returns a string representation of this action\n")
	sb.WriteString("\t * @return a string representation of this action\n")
	sb.WriteString("\t */\n")
	sb.WriteString("\t@java.lang.Override\n")
	sb.WriteString("\tpublic java.lang.String toString()\n")
	sb.WriteString("\t{\n")
	sb.WriteString(fmt.Sprintf("\t\treturn \"%s\";\n", actionName))
	sb.WriteString("\t}\n\n")

	sb.WriteString("\t// BEGIN EXTRA CODE\n")
	if extraCode != "" {
		for line := range strings.SplitSeq(extraCode, "\n") {
			sb.WriteString("\t")
			sb.WriteString(line)
			sb.WriteString("\n")
		}
	}
	sb.WriteString("\t// END EXTRA CODE\n")
	sb.WriteString("}\n")

	_ = returnTypeSimple // legacy parity: retained for future toString-style use
	return sb.String()
}

// getJavaReturnTypeGen mirrors sdk/mpr.getJavaReturnType for gen-typed
// return-type elements. Returns (fullJavaType, simpleName). Defaults to
// Boolean when the element is nil (legacy parity).
func getJavaReturnTypeGen(t element.Element) (string, string) {
	if t == nil {
		return "java.lang.Boolean", "Boolean"
	}
	switch normalizeCodeActionType(t.TypeName()) {
	case "VoidType":
		return "java.lang.Void", "Void"
	case "BooleanType":
		return "java.lang.Boolean", "Boolean"
	case "IntegerType":
		return "java.lang.Integer", "Integer"
	case "LongType":
		return "java.lang.Long", "Long"
	case "DecimalType":
		return "java.math.BigDecimal", "BigDecimal"
	case "StringType":
		return "java.lang.String", "String"
	case "DateTimeType":
		return "java.util.Date", "Date"
	case "EntityType", "ConcreteEntityType":
		return "com.mendix.systemwideinterfaces.core.IMendixObject", "IMendixObject"
	case "ListType":
		return "java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject>", "List"
	default:
		return "java.lang.Object", "Object"
	}
}

// getJavaParamTypeGen mirrors sdk/mpr.getJavaParamType for gen-typed
// parameter-type elements.
func getJavaParamTypeGen(t element.Element) string {
	if t == nil {
		return "java.lang.Object"
	}
	switch normalizeCodeActionType(t.TypeName()) {
	case "BooleanType":
		return "java.lang.Boolean"
	case "IntegerType":
		return "java.lang.Integer"
	case "LongType":
		return "java.lang.Long"
	case "DecimalType":
		return "java.math.BigDecimal"
	case "StringType":
		return "java.lang.String"
	case "DateTimeType":
		return "java.util.Date"
	case "EntityType", "ConcreteEntityType":
		return "com.mendix.systemwideinterfaces.core.IMendixObject"
	case "ListType":
		return "java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject>"
	case "StringTemplateParameterType":
		return "java.lang.String"
	default:
		return "java.lang.Object"
	}
}

// normalizeCodeActionType strips the CodeActions$ or JavaActions$
// namespace prefix from a stored TypeName so the dispatch table only
// has to enumerate the bare type name. Both prefixes are valid in
// fixture MPRs (per cmd_javaactions_gen.go schema-gap notes).
func normalizeCodeActionType(typeName string) string {
	if v, ok := strings.CutPrefix(typeName, "CodeActions$"); ok {
		return v
	}
	if v, ok := strings.CutPrefix(typeName, "JavaActions$"); ok {
		return v
	}
	return typeName
}
