// SPDX-License-Identifier: Apache-2.0

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"text/template"
)

const minedTpl = `// Code generated by cmd/exprgrammar-mine; DO NOT EDIT.

package exprgrammar

// SlotConstraint describes the expected kind of expression at a given slot.
type SlotConstraint struct {
	Kind      string
	Frequency int
	Samples   []string
}

// SlotExpectations is mined from the corpus. Keys are internal SlotPath
// names (e.g., "IfStmt.Condition"). Translation to user-facing context
// happens in mdl/exprcheck/slot_to_context.go.
var SlotExpectations = map[string]SlotConstraint{
{{range .Slots -}}
	{{printf "%q" .Path}}: {Kind: "Unknown", Frequency: {{.Count}}, Samples: []string{
{{range .Samples}}		{{printf "%q" .}},
{{end}}	}},
{{end}}}
`

type tplSlot struct {
	Path    string
	Count   int
	Samples []string
}

func Emit(s *Summary, outPath string) error {
	slots := make([]tplSlot, 0, len(s.AllSlots()))
	for _, k := range s.AllSlots() {
		slots = append(slots, tplSlot{
			Path:    k,
			Count:   s.SlotCount(k),
			Samples: s.SlotSamples(k, 5),
		})
	}
	t, err := template.New("mined").Parse(minedTpl)
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, struct{ Slots []tplSlot }{slots}); err != nil {
		return err
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt %s: %w", outPath, err)
	}
	return os.WriteFile(outPath, formatted, 0o644)
}
