package emitter

// Go text/template strings for generating typed element code from DomainMeta.

const typesTemplate = `// Code generated by mxcli codegen; DO NOT EDIT.
// To modify: edit internal/codegen/supplements.json or internal/codegen/emitter/templates.go,
// then run: go run ./cmd/modelsdk-codegen

package {{.Package}}

import (
	"github.com/mendixlabs/mxcli/modelsdk/codec"
	"github.com/mendixlabs/mxcli/modelsdk/element"
	"github.com/mendixlabs/mxcli/modelsdk/property"
	"go.mongodb.org/mongo-driver/v2/bson"
{{if .Renames}}	"github.com/mendixlabs/mxcli/modelsdk/version"
{{end}})

// Ensure imports are used.
var (
	_ = codec.DefaultRegistry
	_ element.Element = nil
	_ = property.DecodeString
	_ bson.Raw = nil
)
{{range .Types}}{{$typeName := .Name}}
// ────────────────────────────────────────────────────────
// {{$typeName}}
// ────────────────────────────────────────────────────────

type {{$typeName}} struct {
	element.Base{{range .Fields}}
	{{.FieldName}} {{.FieldType}}{{end}}
}
{{range .Fields}}
// {{.GetterName}} returns the value of the {{.PropName}} property.
func (o *{{$typeName}}) {{.GetterName}}() {{.GetterReturn}} {
	return o.{{.FieldName}}.{{.GetterCall}}()
}
{{if .HasSetter}}
// {{.SetterName}} sets the value of the {{.PropName}} property.
func (o *{{$typeName}}) {{.SetterName}}(v {{.SetterArg}}) {
	o.{{.FieldName}}.{{.SetterCall}}(v)
}
{{end}}{{if .HasAdder}}
// {{.AdderName}} appends a child element to the {{.PropName}} list.
func (o *{{$typeName}}) {{.AdderName}}(v {{.AdderArg}}) {
	o.{{.FieldName}}.Append(v)
}
{{end}}{{if .IsList}}
// {{.RemoverName}} removes the element at the given index from the {{.PropName}} list.
func (o *{{$typeName}}) {{.RemoverName}}(index int) {
	o.{{.FieldName}}.Remove(index)
}
{{end}}{{end}}
// InitFromRaw populates lazy-decoded property holders from raw BSON.
func (o *{{$typeName}}) InitFromRaw(raw bson.Raw) {
{{- range .Fields}}{{if .NeedsInit}}
	o.{{.FieldName}}.Init(raw)
{{- end}}{{if .IsPartChild}}{{if .IsList}}
	if children, err := codec.DecodeChildren(raw, "{{.BSONKey}}"); err == nil {
		for _, child := range children {
			o.{{.FieldName}}.AppendFromDecode(child)
		}
	}
{{- else}}
	if child, err := codec.DecodeChild(raw, "{{.BSONKey}}"); err == nil {
		o.{{.FieldName}}.SetFromDecode(child)
	}
{{- end}}{{end}}{{if .IsRef}}
	if val, err := raw.LookupErr("{{.BSONKey}}"); err == nil {
		if s, ok := val.StringValueOK(); ok { o.{{.FieldName}}.SetFromDecode(s) }
	}
{{- end}}{{if .IsRefList}}
	if val, err := raw.LookupErr("{{.BSONKey}}"); err == nil {
		if arr, ok := val.ArrayOK(); ok {
			vals, _ := arr.Values()
			qnames := make([]string, 0, len(vals))
			for _, v := range vals {
				if s, ok := v.StringValueOK(); ok { qnames = append(qnames, s) }
			}
			o.{{.FieldName}}.SetFromDecode(qnames)
		}
	}
{{- end}}{{if .IsIdRef}}
	if val, err := raw.LookupErr("{{.BSONKey}}"); err == nil {
		if s, ok := val.StringValueOK(); ok {
			o.{{.FieldName}}.SetFromDecode(element.ID(s))
		} else if _, bdata, bok := val.BinaryOK(); bok {
			o.{{.FieldName}}.SetFromDecode(element.ID(codec.BinaryToUUID(bdata)))
		}
	}
{{- end}}{{if .IsEnum}}
	if val, err := raw.LookupErr("{{.BSONKey}}"); err == nil {
		if s, ok := val.StringValueOK(); ok { o.{{.FieldName}}.SetFromDecode(s) }
	}
{{- end}}{{if .IsEnumList}}
	if val, err := raw.LookupErr("{{.BSONKey}}"); err == nil {
		if arr, ok := val.ArrayOK(); ok {
			vals, _ := arr.Values()
			items := make([]string, 0, len(vals))
			for _, v := range vals {
				if s, ok := v.StringValueOK(); ok { items = append(items, s) }
			}
			o.{{.FieldName}}.SetFromDecode(items)
		}
	}
{{- end}}{{end}}
}
{{end}}
// ────────────────────────────────────────────────────────
// Factory functions
// ────────────────────────────────────────────────────────
{{range .Types}}{{if not .IsAbstract}}
// init{{.Name}} creates a {{.Name}} with properties wired but NOT marked dirty.
// Used by the registry for decoding existing elements from BSON.
// When a storage alias exists, init uses the STORAGE name (what Mendix uses in BSON).
func init{{.Name}}() *{{.Name}} {
	o := &{{.Name}}{}
	o.SetTypeName("{{if and .StorageAlias (not .IsVersionRename)}}{{.StorageAlias}}{{else}}{{.StructureTypeName}}{{end}}"){{range .Fields}}
	o.{{.FieldName}} = {{.Constructor}}
	o.{{.FieldName}}.Bind(&o.Base, {{.FieldIndex}}){{end}}
	o.SetProperties([]element.Property{ {{- range .Fields}}o.{{.FieldName}}, {{end -}} })
	return o
}

// New{{.Name}} creates a new {{.Name}} for user code. Marked dirty (bit 63 = new element).
func New{{.Name}}() *{{.Name}} {
	o := init{{.Name}}()
	// TODO: applyDefaults(o) — populate mandatory fields from reflection-data
	// See docs/superpowers/specs/2026-04-22-modelsdk-tech-debt-design.md Fix 4
	o.MarkDirty(63)
	return o
}
{{end}}{{end}}
{{range .Renames}}
// New{{.FuncBaseName}}ForVersion returns the version-correct concrete type for the
// {{.NewGoName}} / {{.OldGoName}} activity.
//   < {{.Since}} → *{{.OldGoName}} ($Type "{{.OldTypeName}}")
//   ≥ {{.Since}} → *{{.NewGoName}} ($Type "{{.NewTypeName}}")
func New{{.FuncBaseName}}ForVersion(v version.Version) element.Element {
	if v.Compare(version.Parse("{{.Since}}")) >= 0 {
		return New{{.NewGoName}}()
	}
	return New{{.OldGoName}}()
}
{{end}}
func init() {
{{- range .Types}}{{if not .IsAbstract}}
{{- if .StorageAlias}}
	codec.DefaultRegistry.Register("{{.StructureTypeName}}", func() element.Element {
		o := init{{.Name}}()
		o.SetTypeName("{{.StructureTypeName}}")
		return o
	})
	codec.DefaultRegistry.Register("{{.StorageAlias}}", func() element.Element {
		return init{{.Name}}()
	})
{{- else}}
	codec.DefaultRegistry.Register("{{.StructureTypeName}}", func() element.Element {
		return init{{.Name}}()
	})
{{- end}}{{end}}{{end}}
}
`

const enumsTemplate = `// Code generated by mxcli codegen; DO NOT EDIT.
// To modify: edit internal/codegen/supplements.json or internal/codegen/emitter/templates.go,
// then run: go run ./cmd/modelsdk-codegen

package {{.Package}}
{{range .Enums}}
// {{.Name}} enumerates the possible values for the {{.Name}} type.
type {{.Name}} = string

const ({{range .Values}}
	{{.GoConst}} {{.TypeAlias}} = "{{.Name}}"{{end}}
)
{{end}}
`

// versionTemplate emits a map literal per class that has version information.
// Consumers can use version.TypeVersionInfo directly.
const versionTemplate = `// Code generated by mxcli codegen; DO NOT EDIT.
// To modify: edit internal/codegen/supplements.json or internal/codegen/emitter/templates.go,
// then run: go run ./cmd/modelsdk-codegen

package {{.Package}}

import "github.com/mendixlabs/mxcli/modelsdk/version"

// VersionInfos maps structure-type names to their TypeVersionInfo.
var VersionInfos = map[string]version.TypeVersionInfo{
{{- range .Versions}}
	"{{.StructureTypeName}}": {
		{{- if .ClassIntroduced}}Introduced: "{{.ClassIntroduced}}",{{end}}
		{{- if .ClassDeleted}}Deleted: "{{.ClassDeleted}}",{{end}}
		Properties: map[string]version.PropertyVersionInfo{
		{{- range .Props}}
			"{{.Name}}": {
				{{- if .Introduced}}Introduced: "{{.Introduced}}", {{end -}}
				{{- if .Deleted}}Deleted: "{{.Deleted}}", {{end -}}
				{{- if .Required}}Required: true, {{end -}}
				{{- if .Public}}Public: true, {{end -}}
			},
		{{- end}}
		},
	},
{{- end}}
}

func init() {
	for name, info := range VersionInfos {
		version.DefaultVersionRegistry.Register(name, info)
	}
}
`
