package emitter

const descriptorsTemplate = `// Code generated by mxcli codegen; DO NOT EDIT.
// To modify: edit internal/codegen/supplements.json or internal/codegen/emitter/templates.go,
// then run: go run ./cmd/modelsdk-codegen

package {{.Package}}
{{- $hasDescs := false}}
{{- range .Types}}{{if .Fields}}{{$hasDescs = true}}{{end}}{{end}}
{{- if $hasDescs}}

import "github.com/mendixlabs/mxcli/modelsdk/codec"

func init() {
{{- range .Types}}{{if .Fields}}
	codec.DefaultDescRegistry.Register("{{.StructureTypeName}}", &codec.TypeDesc{
		TypeName: "{{.StructureTypeName}}",
		Properties: []codec.PropDesc{
		{{- range .Fields}}
			{Name: "{{.PropName}}", BSONKey: "{{.BSONKey}}", Kind: codec.{{.DescriptorKind}}, RefType: "{{.TargetType}}"},
		{{- end}}
		},
	})
{{- if .StorageAlias}}
	codec.DefaultDescRegistry.Register("{{.StorageAlias}}", &codec.TypeDesc{
		TypeName: "{{.StorageAlias}}",
		Properties: []codec.PropDesc{
		{{- range .Fields}}
			{Name: "{{.PropName}}", BSONKey: "{{.BSONKey}}", Kind: codec.{{.DescriptorKind}}, RefType: "{{.TargetType}}"},
		{{- end}}
		},
	})
{{- end}}
{{- end}}{{end}}
}
{{- end}}
`
