package emitter

const refsTemplate = `// Code generated by mxcli codegen; DO NOT EDIT.
// To modify: edit internal/codegen/supplements.json or internal/codegen/emitter/templates.go,
// then run: go run ./cmd/modelsdk-codegen

package {{.Package}}
{{- $hasRefs := false}}
{{- range .Types}}{{if .Refs}}{{$hasRefs = true}}{{end}}{{end}}
{{- if $hasRefs}}

import "github.com/mendixlabs/mxcli/modelsdk/codec"

func init() {
{{- range .Types}}{{if .Refs}}
	codec.DefaultRefRegistry.RegisterRefs("{{.StructureTypeName}}", []codec.RefMeta{
	{{- range .Refs}}
		{Prop: "{{.Prop}}", Kind: codec.{{.Kind}}, Target: "{{.Target}}"},
	{{- end}}
	})
{{- if .StorageAlias}}
	codec.DefaultRefRegistry.RegisterRefs("{{.StorageAlias}}", []codec.RefMeta{
	{{- range .Refs}}
		{Prop: "{{.Prop}}", Kind: codec.{{.Kind}}, Target: "{{.Target}}"},
	{{- end}}
	})
{{- end}}
{{- end}}{{end}}
}
{{- end}}
`
