// SPDX-License-Identifier: Apache-2.0

package executor

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/mendixlabs/mxcli/modelsdk/element"
	genJA "github.com/mendixlabs/mxcli/modelsdk/gen/javaactions"
	genJSA "github.com/mendixlabs/mxcli/modelsdk/gen/javascriptactions"
)

// readJavaScriptActionSource extracts user code and extra code from the
// project's javascriptsource/<module>/actions/<action>.js file.
// Returns (userCode, extraCode, sourcePath) where sourcePath is the canonical
// relative path even when the file is absent, so callers can show it to the user.
func readJavaScriptActionSource(mprPath, moduleName, actionName string) (userCode, extraCode, sourcePath string) {
	relPath := filepath.Join("javascriptsource", moduleName, "actions", actionName+".js")
	if mprPath == "" {
		return "", "", relPath
	}
	projectRoot := filepath.Dir(mprPath)
	jsPath := filepath.Join(projectRoot, relPath)
	content, err := os.ReadFile(jsPath)
	if err != nil {
		lowerPath := filepath.Join("javascriptsource", strings.ToLower(moduleName), "actions", actionName+".js")
		jsPath = filepath.Join(projectRoot, lowerPath)
		content, err = os.ReadFile(jsPath)
		if err != nil {
			return "", "", relPath
		}
		relPath = lowerPath
	}
	sourcePath = relPath
	source := string(content)

	if beginIdx := strings.Index(source, "// BEGIN USER CODE"); beginIdx != -1 {
		if endIdx := strings.Index(source, "// END USER CODE"); endIdx != -1 && endIdx > beginIdx {
			uc := source[beginIdx+len("// BEGIN USER CODE") : endIdx]
			uc = strings.TrimPrefix(uc, "\n")
			uc = strings.TrimSuffix(uc, "\n")
			uc = strings.TrimRight(uc, " \t")
			userCode = uc
		}
	}
	if beginIdx := strings.Index(source, "// BEGIN EXTRA CODE"); beginIdx != -1 {
		if endIdx := strings.Index(source, "// END EXTRA CODE"); endIdx != -1 && endIdx > beginIdx {
			ec := source[beginIdx+len("// BEGIN EXTRA CODE") : endIdx]
			ec = strings.TrimSpace(ec)
			if ec != "" {
				extraCode = ec
			}
		}
	}
	return userCode, extraCode, sourcePath
}

// writeJavaScriptActionSource writes or overwrites the JS action source file at
// javascriptsource/<lowercase-module>/actions/<ActionName>.js.
func writeJavaScriptActionSource(mprPath, moduleName, actionName, imports, extraCode, userCode string, paramNames []string) error {
	if mprPath == "" {
		return fmt.Errorf("writeJavaScriptActionSource: mprPath is empty")
	}
	projectRoot := filepath.Dir(mprPath)
	modLower := strings.ToLower(moduleName)
	dir := filepath.Join(projectRoot, "javascriptsource", modLower, "actions")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create js action dir: %w", err)
	}

	var sb strings.Builder
	sb.WriteString("// This file was generated by Mendix Studio Pro.\n")
	sb.WriteString("//\n")
	sb.WriteString("// WARNING: Only the following code will be retained when actions are regenerated:\n")
	sb.WriteString("// - the import list\n")
	sb.WriteString("// - the code between BEGIN USER CODE and END USER CODE\n")
	sb.WriteString("// - the code between BEGIN EXTRA CODE and END EXTRA CODE\n")
	sb.WriteString("// Other code you write will be lost the next time you deploy the project.\n")
	sb.WriteString("import { Big } from \"big.js\";\n")
	if imports != "" {
		for _, line := range strings.Split(imports, "\n") {
			line = strings.TrimSpace(line)
			if line == "" || line == `import { Big } from "big.js";` {
				continue
			}
			sb.WriteString(line)
			sb.WriteString("\n")
		}
	}
	sb.WriteString("\n")
	sb.WriteString("// BEGIN EXTRA CODE\n")
	if extraCode != "" {
		sb.WriteString(extraCode)
		if !strings.HasSuffix(extraCode, "\n") {
			sb.WriteString("\n")
		}
	}
	sb.WriteString("// END EXTRA CODE\n")
	sb.WriteString("\n")
	// JSDoc
	sb.WriteString("/**\n")
	for _, pn := range paramNames {
		sb.WriteString(" * @param {string} ")
		sb.WriteString(pn)
		sb.WriteString("\n")
	}
	sb.WriteString(" * @returns {Promise.<void>}\n")
	sb.WriteString(" */\n")

	sb.WriteString("export async function ")
	sb.WriteString(actionName)
	sb.WriteString("(")
	for i, pn := range paramNames {
		if i > 0 {
			sb.WriteString(", ")
		}
		sb.WriteString(pn)
	}
	sb.WriteString(") {\n")
	sb.WriteString("\t// BEGIN USER CODE\n")
	if userCode != "" {
		for _, line := range strings.Split(userCode, "\n") {
			sb.WriteString("\t")
			sb.WriteString(line)
			sb.WriteString("\n")
		}
	}
	sb.WriteString("\t// END USER CODE\n")
	sb.WriteString("}\n")

	jsPath := filepath.Join(dir, actionName+".js")
	return os.WriteFile(jsPath, []byte(sb.String()), 0644)
}

// javaActionParametersOf returns the parameter list, preferring the
// legacy ParametersItems (BSON key "Parameters" — what Studio Pro emits
// for existing elements) over the newer ActionParametersItems
// (BSON key "ActionParameters"). See schema-gap note (3) at top of file.
func javaActionParametersOf(ja *genJA.JavaAction) []element.Element {
	if ja == nil {
		return nil
	}
	if items := ja.ParametersItems(); len(items) > 0 {
		return items
	}
	return ja.ActionParametersItems()
}

// javaActionTypeParametersOf is the type-parameter twin of
// javaActionParametersOf. Same precedence rule.
func javaActionTypeParametersOf(ja *genJA.JavaAction) []element.Element {
	if ja == nil {
		return nil
	}
	if items := ja.TypeParametersItems(); len(items) > 0 {
		return items
	}
	return ja.ActionTypeParametersItems()
}

// javaActionReturnTypeElement returns the return-type sub-element,
// preferring JavaReturnType (legacy "JavaReturnType" BSON key) over
// ActionReturnType (newer "ActionReturnType"). See schema-gap note (3).
func javaActionReturnTypeElement(ja *genJA.JavaAction) element.Element {
	if ja == nil {
		return nil
	}
	if rt := ja.JavaReturnType(); rt != nil {
		return rt
	}
	return ja.ActionReturnType()
}

// javaScriptActionReturnTypeElement mirrors javaActionReturnTypeElement for
// JavaScript actions. Studio Pro stores the return type under the legacy
// "JavaReturnType" BSON key (same as Java actions), but genJSA.JavaScriptAction
// only exposes "ActionReturnType" via its typed getter — which is absent in
// Studio-Pro-emitted BSON and therefore always nil. We raw-read the legacy key
// via genJA.DecodeChildElement so that void/Nothing and typed returns are not lost.
func javaScriptActionReturnTypeElement(jsa *genJSA.JavaScriptAction) element.Element {
	if jsa == nil {
		return nil
	}
	// Prefer the legacy JavaReturnType field written by Studio Pro.
	if rt := genJA.DecodeChildElement(jsa, "JavaReturnType"); rt != nil {
		return rt
	}
	// Fall back to ActionReturnType set by our own write path.
	return jsa.ActionReturnType()
}

// javaActionParameterParameterType returns the parameter's type sub-
// element, preferring ParameterType (legacy "ParameterType" BSON key —
// often a BasicParameterType wrapper) over JavaType / ActionParameterType
// (newer keys). The format helper above peels BasicParameterType when
// it gets back an outer wrapper.
func javaActionParameterParameterType(p *genJA.JavaActionParameter) element.Element {
	if p == nil {
		return nil
	}
	if pt := p.ParameterType(); pt != nil {
		return pt
	}
	if pt := p.JavaType(); pt != nil {
		return pt
	}
	return p.ActionParameterType()
}

// javaActionMicroflowActionInfoOf returns the modeler/action info sub-
// element, preferring MicroflowActionInfo (legacy) over ModelerActionInfo
// (newer) for Studio-Pro-fixture compatibility.
func javaActionMicroflowActionInfoOf(ja *genJA.JavaAction) element.Element {
	if ja == nil {
		return nil
	}
	if mai := ja.MicroflowActionInfo(); mai != nil {
		return mai
	}
	return ja.ModelerActionInfo()
}

// readJavaScriptActionImports reads all `import ...` lines from the JS
// action source file, joined by newline. Returns "" when the file is
// absent. Used by describe to populate the `imports $$ $$` block.
func readJavaScriptActionImports(mprPath, moduleName, actionName string) string {
	if mprPath == "" {
		return ""
	}
	projectRoot := filepath.Dir(mprPath)
	candidates := []string{
		filepath.Join(projectRoot, "javascriptsource", moduleName, "actions", actionName+".js"),
		filepath.Join(projectRoot, "javascriptsource", strings.ToLower(moduleName), "actions", actionName+".js"),
	}
	for _, jsPath := range candidates {
		content, err := os.ReadFile(jsPath)
		if err != nil {
			continue
		}
		var importLines []string
		for _, line := range strings.Split(string(content), "\n") {
			t := strings.TrimSpace(line)
			if strings.HasPrefix(t, "import ") {
				importLines = append(importLines, t)
			}
		}
		return strings.Join(importLines, "\n")
	}
	return ""
}

// readJavaActionUserCode reads the Java source file and extracts the
// user code section between BEGIN USER CODE / END USER CODE markers.
// Mirror of the helper that lived in the now-deleted cmd_javaactions.go.
func readJavaActionUserCode(mprPath, moduleName, actionName string) string {
	if mprPath == "" {
		return ""
	}
	projectRoot := filepath.Dir(mprPath)
	moduleNameLower := strings.ToLower(moduleName)
	javaPath := filepath.Join(projectRoot, "javasource", moduleNameLower, "actions", actionName+".java")
	content, err := os.ReadFile(javaPath)
	if err != nil {
		return ""
	}
	source := string(content)
	beginMarker := "// begin user CODE"
	endMarker := "// end user CODE"
	beginIdx := strings.Index(source, beginMarker)
	endIdx := strings.Index(source, endMarker)
	if beginIdx == -1 || endIdx == -1 || endIdx <= beginIdx {
		return ""
	}
	userCode := source[beginIdx+len(beginMarker) : endIdx]
	userCode = strings.TrimPrefix(userCode, "\n")
	userCode = strings.TrimSuffix(userCode, "\n")
	userCode = strings.TrimRight(userCode, " \t")
	return userCode
}

// readJavaActionSource reads all three user-editable sections from a .java file:
// userCode (BEGIN/END USER CODE), imports (all import lines), extraCode
// (BEGIN/END EXTRA CODE). Returns empty values when the file is absent or
// markers are not found. Uses uppercase markers that match what
// generateJavaSourceGen writes.
func readJavaActionSource(mprPath, moduleName, actionName string) (userCode string, imports []string, extraCode string) {
	if mprPath == "" {
		return
	}
	projectRoot := filepath.Dir(mprPath)
	moduleNameLower := strings.ToLower(moduleName)
	javaPath := filepath.Join(projectRoot, "javasource", moduleNameLower, "actions", actionName+".java")
	content, err := os.ReadFile(javaPath)
	if err != nil {
		return
	}
	src := string(content)

	if bi := strings.Index(src, "// BEGIN USER CODE"); bi != -1 {
		if ei := strings.Index(src, "// END USER CODE"); ei != -1 && ei > bi {
			uc := src[bi+len("// BEGIN USER CODE") : ei]
			uc = strings.TrimPrefix(uc, "\n")
			uc = strings.TrimSuffix(uc, "\n")
			userCode = strings.TrimRight(uc, " \t")
		}
	}

	for _, line := range strings.Split(src, "\n") {
		t := strings.TrimSpace(line)
		if strings.HasPrefix(t, "import ") && strings.HasSuffix(t, ";") {
			imports = append(imports, t)
		}
	}

	if bi := strings.Index(src, "// BEGIN EXTRA CODE"); bi != -1 {
		if ei := strings.Index(src, "// END EXTRA CODE"); ei != -1 && ei > bi {
			ec := src[bi+len("// BEGIN EXTRA CODE") : ei]
			ec = strings.TrimSpace(ec)
			if ec != "" {
				extraCode = ec
			}
		}
	}
	return
}
