// SPDX-License-Identifier: Apache-2.0
package executor

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	genJA "github.com/mendixlabs/mxcli/modelsdk/gen/javaactions"
	genJSA "github.com/mendixlabs/mxcli/modelsdk/gen/javascriptactions"
)

// TestJavaScriptActionReturnTypeElement_ReadsJavaReturnTypeFallback verifies
// that javaScriptActionReturnTypeElement reads the legacy "JavaReturnType" BSON
// field (used by Studio Pro) when ActionReturnType is absent.
// This is the root cause of the "returns clause missing" bug: Studio Pro stores
// the return type under JavaReturnType, but genJSA.JavaScriptAction.ActionReturnType()
// reads "ActionReturnType" — which is absent → nil → the returns line is skipped.
func TestJavaScriptActionReturnTypeElement_ReadsJavaReturnTypeFallback(t *testing.T) {
	// A fresh genJSA.JavaScriptAction has no ActionReturnType set.
	jsa := genJSA.NewJavaScriptAction()

	// Confirm ActionReturnType() returns nil (the buggy state).
	if jsa.ActionReturnType() != nil {
		t.Skip("ActionReturnType unexpectedly non-nil on new element — test assumption changed")
	}

	// javaScriptActionReturnTypeElement must fall back to reading "JavaReturnType"
	// via genJA.DecodeChildElement. For a plain new element (no raw BSON), both
	// fields are absent, so the result is nil. That is then formatted as "Void"
	// by formatJavaActionReturnTypeGen — which is the correct behaviour.
	rt := javaScriptActionReturnTypeElement(jsa)
	// nil is the correct result for a void/nothing return type.
	// formatJavaActionReturnTypeGen(nil, ...) = "Void", which gets emitted.
	_ = rt

	// The describe output must include "returns" regardless of nil.
	formatted := formatJavaActionReturnTypeGen(javaScriptActionReturnTypeElement(jsa), nil)
	if formatted == "" {
		t.Errorf("formatJavaActionReturnTypeGen returned empty string for nil element; want 'Void'")
	}
	// Confirm the helper itself exists (compilation test).
	_ = javaScriptActionReturnTypeElement
}

// TestDescribeJavaScriptAction_AlwaysEmitsReturns verifies that the describe
// path always writes a "returns" clause even when ActionReturnType is nil
// (i.e. void/Nothing return type stored only in legacy JavaReturnType field).
func TestDescribeJavaScriptAction_AlwaysEmitsReturns(t *testing.T) {
	// The describe function is only callable with a live ExecContext, so we
	// test the building-block functions that were the root cause instead.

	// A new JavaScriptAction has no ActionReturnType (nil).
	jsa := genJSA.NewJavaScriptAction()
	if jsa.ActionReturnType() != nil {
		t.Skip("assumption changed")
	}

	// With the old buggy code: jsa.ActionReturnType() == nil → `returns` line skipped.
	// With the fix: javaScriptActionReturnTypeElement(jsa) is called, then always emitted.
	typeParams := jsa.ActionTypeParametersItems() // empty
	result := formatJavaActionReturnTypeGen(javaScriptActionReturnTypeElement(jsa), typeParams)
	if result == "" {
		t.Errorf("formatJavaActionReturnTypeGen returned empty string; want 'Void'")
	}

	// Verify that a BooleanType return is also correctly formatted.
	jsaBool := genJSA.NewJavaScriptAction()
	boolType := genJA.NewBooleanType()
	jsaBool.SetActionReturnType(boolType)
	resultBool := formatJavaActionReturnTypeGen(javaScriptActionReturnTypeElement(jsaBool), nil)
	if resultBool != "Boolean" {
		t.Errorf("formatJavaActionReturnTypeGen(BooleanType) = %q, want 'Boolean'", resultBool)
	}
}

// TestReadJavaScriptActionSource_ExtractsUserCode verifies that readJavaScriptActionSource
// correctly reads user code from a JS file using Mendix's uppercase BEGIN/END USER CODE markers.
func TestReadJavaScriptActionSource_ExtractsUserCode(t *testing.T) {
	tmpDir := t.TempDir()
	mprPath := filepath.Join(tmpDir, "test.mpr")
	if err := os.WriteFile(mprPath, []byte{}, 0644); err != nil {
		t.Fatal(err)
	}
	jsDir := filepath.Join(tmpDir, "javascriptsource", "MyModule", "actions")
	if err := os.MkdirAll(jsDir, 0755); err != nil {
		t.Fatal(err)
	}
	// This is the format Mendix Studio Pro generates.
	jsContent := "// This file was generated by Mendix Studio Pro.\n" +
		"import { Big } from \"big.js\";\n" +
		"\n" +
		"// BEGIN EXTRA CODE\n" +
		"const helper = () => 42;\n" +
		"// END EXTRA CODE\n" +
		"\n" +
		"export async function MyAction(p1) {\n" +
		"\t// BEGIN USER CODE\n" +
		"\treturn p1 + 1;\n" +
		"\t// END USER CODE\n" +
		"}\n"
	if err := os.WriteFile(filepath.Join(jsDir, "MyAction.js"), []byte(jsContent), 0644); err != nil {
		t.Fatal(err)
	}

	userCode, extraCode, sourcePath := readJavaScriptActionSource(mprPath, "MyModule", "MyAction")

	if !strings.Contains(userCode, "return p1 + 1;") {
		t.Errorf("userCode = %q, want to contain 'return p1 + 1;'", userCode)
	}
	if !strings.Contains(extraCode, "helper") {
		t.Errorf("extraCode = %q, want to contain 'helper'", extraCode)
	}
	if !strings.Contains(sourcePath, "javascriptsource") {
		t.Errorf("sourcePath = %q, want to contain 'javascriptsource'", sourcePath)
	}
	if !strings.Contains(sourcePath, "MyAction.js") {
		t.Errorf("sourcePath = %q, want to contain 'MyAction.js'", sourcePath)
	}
}

// TestReadJavaScriptActionSource_LowercaseModuleFallback verifies that readJavaScriptActionSource
// falls back to lowercase module name when the exact-case path is not found.
func TestReadJavaScriptActionSource_LowercaseModuleFallback(t *testing.T) {
	tmpDir := t.TempDir()
	mprPath := filepath.Join(tmpDir, "test.mpr")
	if err := os.WriteFile(mprPath, []byte{}, 0644); err != nil {
		t.Fatal(err)
	}
	// Only the lowercase path exists (as Mendix Studio Pro stores it).
	jsDir := filepath.Join(tmpDir, "javascriptsource", "mymodule", "actions")
	if err := os.MkdirAll(jsDir, 0755); err != nil {
		t.Fatal(err)
	}
	jsContent := "export async function DoIt() {\n\t// BEGIN USER CODE\n\treturn true;\n\t// END USER CODE\n}\n"
	if err := os.WriteFile(filepath.Join(jsDir, "DoIt.js"), []byte(jsContent), 0644); err != nil {
		t.Fatal(err)
	}

	userCode, _, sourcePath := readJavaScriptActionSource(mprPath, "MyModule", "DoIt")

	if !strings.Contains(userCode, "return true;") {
		t.Errorf("userCode = %q, want to contain 'return true;'", userCode)
	}
	if sourcePath == "" {
		t.Error("sourcePath should not be empty when file is found")
	}
}

// TestReadJavaScriptActionSource_ReturnsExpectedPathWhenNotFound verifies that
// readJavaScriptActionSource returns the expected (not-found) source path even when
// the file doesn't exist, so describe output can show the user where to look.
func TestReadJavaScriptActionSource_ReturnsExpectedPathWhenNotFound(t *testing.T) {
	tmpDir := t.TempDir()
	mprPath := filepath.Join(tmpDir, "test.mpr")
	if err := os.WriteFile(mprPath, []byte{}, 0644); err != nil {
		t.Fatal(err)
	}

	_, _, sourcePath := readJavaScriptActionSource(mprPath, "FeedbackModule", "JS_isStrictMode")

	// Even when file is not found, should return the expected canonical path.
	if !strings.Contains(sourcePath, "javascriptsource") {
		t.Errorf("sourcePath = %q, want to contain 'javascriptsource'", sourcePath)
	}
	if !strings.Contains(sourcePath, "JS_isStrictMode.js") {
		t.Errorf("sourcePath = %q, want to contain 'JS_isStrictMode.js'", sourcePath)
	}
}

func TestWriteJavaScriptActionSource_CreatesFileWithAllSections(t *testing.T) {
	tmpDir := t.TempDir()
	mprPath := filepath.Join(tmpDir, "test.mpr")
	if err := os.WriteFile(mprPath, []byte{}, 0644); err != nil {
		t.Fatal(err)
	}

	imports := "import { Big } from \"big.js\";\nimport \"mx-global\";"
	extraCode := "function helper() { return 42; }"
	userCode := "return helper();"

	if err := writeJavaScriptActionSource(mprPath, "MyModule", "MyAction", imports, extraCode, userCode, []string{"base64"}); err != nil {
		t.Fatalf("writeJavaScriptActionSource: %v", err)
	}

	jsPath := filepath.Join(tmpDir, "javascriptsource", "mymodule", "actions", "MyAction.js")
	content, err := os.ReadFile(jsPath)
	if err != nil {
		t.Fatalf("read written file: %v", err)
	}
	src := string(content)

	if !strings.Contains(src, "This file was generated by Mendix Studio Pro") {
		t.Error("missing header")
	}
	if !strings.Contains(src, `import { Big } from "big.js"`) {
		t.Error("missing big.js import")
	}
	if !strings.Contains(src, `import "mx-global"`) {
		t.Error("missing mx-global import")
	}
	if !strings.Contains(src, "// BEGIN EXTRA CODE") || !strings.Contains(src, "// END EXTRA CODE") {
		t.Error("missing EXTRA CODE markers")
	}
	if !strings.Contains(src, "function helper()") {
		t.Error("missing extra code")
	}
	if !strings.Contains(src, "\t// BEGIN USER CODE") {
		t.Error("missing BEGIN USER CODE (with tab)")
	}
	if !strings.Contains(src, "\t// END USER CODE") {
		t.Error("missing END USER CODE (with tab)")
	}
	if !strings.Contains(src, "return helper();") {
		t.Error("missing user code")
	}
	if !strings.Contains(src, "export async function MyAction(") {
		t.Error("missing function signature")
	}
}

func TestWriteJavaScriptActionSource_EmptySectionsOmitted(t *testing.T) {
	tmpDir := t.TempDir()
	mprPath := filepath.Join(tmpDir, "test.mpr")
	if err := os.WriteFile(mprPath, []byte{}, 0644); err != nil {
		t.Fatal(err)
	}

	if err := writeJavaScriptActionSource(mprPath, "Mod", "Act", "", "", "throw new Error('not implemented');", nil); err != nil {
		t.Fatalf("writeJavaScriptActionSource: %v", err)
	}

	jsPath := filepath.Join(tmpDir, "javascriptsource", "mod", "actions", "Act.js")
	content, err := os.ReadFile(jsPath)
	if err != nil {
		t.Fatalf("read file: %v", err)
	}
	src := string(content)

	if !strings.Contains(src, "// BEGIN EXTRA CODE") {
		t.Error("EXTRA CODE section should always be present")
	}
	if strings.Contains(src, `import "mx-global"`) {
		t.Error("mx-global should not be present when imports is empty")
	}
}

func TestReadJavaActionSource_AllSections(t *testing.T) {
	tmpDir := t.TempDir()
	mprPath := filepath.Join(tmpDir, "test.mpr")
	if err := os.WriteFile(mprPath, []byte{}, 0644); err != nil {
		t.Fatal(err)
	}
	javaDir := filepath.Join(tmpDir, "javasource", "mymod", "actions")
	if err := os.MkdirAll(javaDir, 0755); err != nil {
		t.Fatal(err)
	}
	javaContent := "package mymod.actions;\n" +
		"import com.mendix.systemwideinterfaces.core.IContext;\n" +
		"import java.util.List;\n" +
		"public class MyAction extends UserAction<java.lang.String> {\n" +
		"\tpublic java.lang.String executeAction() throws Exception {\n" +
		"\t\t// BEGIN USER CODE\n" +
		"\t\treturn this.Input.trim();\n" +
		"\t\t// END USER CODE\n" +
		"\t}\n" +
		"\t// BEGIN EXTRA CODE\n" +
		"\tprivate String helper() { return \"\"; }\n" +
		"\t// END EXTRA CODE\n" +
		"}\n"
	if err := os.WriteFile(filepath.Join(javaDir, "MyAction.java"), []byte(javaContent), 0644); err != nil {
		t.Fatal(err)
	}

	userCode, imports, extraCode := readJavaActionSource(mprPath, "mymod", "MyAction")

	if !strings.Contains(userCode, "return this.Input.trim();") {
		t.Errorf("userCode = %q", userCode)
	}
	if !strings.Contains(extraCode, "helper") {
		t.Errorf("extraCode = %q", extraCode)
	}
	hasListImport := false
	for _, imp := range imports {
		if strings.Contains(imp, "java.util.List") {
			hasListImport = true
		}
	}
	if !hasListImport {
		t.Errorf("imports = %v, want java.util.List", imports)
	}
}
