// SPDX-License-Identifier: Apache-2.0

package executor

import (
	"bytes"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mendixlabs/mxcli/mdl/ast"
	"github.com/mendixlabs/mxcli/mdl/backend/mock"
	mprbackend "github.com/mendixlabs/mxcli/mdl/backend/mpr"
	mprrepos "github.com/mendixlabs/mxcli/mdl/backend/mpr/repos"
	"github.com/mendixlabs/mxcli/mdl/visitor"
)

// TestDescribeJavaScriptActionGen_SourceFileComplete verifies that
// describeJavaScriptActionGen reads and outputs ALL sections from the
// JavaScript source file (imports, extra, code) when the file exists
// on disk. Before the fix, the source-path helper was discarded and
// the imports/extra/code blocks could be silently empty even when the
// source file existed.
func TestDescribeJavaScriptActionGen_SourceFileComplete(t *testing.T) {
	w := openMprWriterForTest(t)
	path := w.ConcreteReader().Path()
	projectRoot := filepath.Dir(path)

	be, err := mprbackend.NewFromPath(path)
	if err != nil {
		t.Fatalf("mprbackend.NewFromPath(%s): %v", path, err)
	}
	t.Cleanup(func() { _ = be.Disconnect() })

	ctx := &ExecContext{
		Backend: be,
			MprPath: path,
		JavaActions: mprrepos.NewJavaActionRepository(w), JavaScriptActions: mprrepos.NewJavaScriptActionRepository(w),
		Output: io.Discard,
	}
	ctx.initRoles()
	ctx.ensureCache()

	// Resolve a real JS action from the fixture.
	h, err := getHierarchy(ctx)
	if err != nil {
		t.Fatalf("getHierarchy: %v", err)
	}
	pairs, err := listJavaScriptActionsWithContainerGen(ctx)
	if err != nil {
		t.Fatalf("listJavaScriptActionsWithContainerGen: %v", err)
	}
	if len(pairs) == 0 {
		t.Skip("fixture has no JS actions")
	}
	first := pairs[0].Elem
	modID := h.FindModuleID(modelIDFromElementID(pairs[0].ContainerID))
	modName := h.GetModuleName(modID)

	// Create a JS source file in the temp fixture dir with all three sections.
	moduleDir := filepath.Join(projectRoot, "javascriptsource", strings.ToLower(modName), "actions")
	if err := os.MkdirAll(moduleDir, 0755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	jsPath := filepath.Join(moduleDir, first.Name()+".js")
	jsContent := `// This file was generated by Mendix Studio Pro.
import { Big } from "big.js";
import MyType from "./MyType";

// BEGIN EXTRA CODE
function helper() { return 42; }
// END EXTRA CODE

export async function ` + first.Name() + `(input) {
	// BEGIN USER CODE
	const result = helper();
	return result;
	// END USER CODE
}
`
	if err := os.WriteFile(jsPath, []byte(jsContent), 0644); err != nil {
		t.Fatalf("write source file: %v", err)
	}

	var buf bytes.Buffer
	ctx.Output = &buf
	rebuildDeps(ctx)

	if err := describeJavaScriptActionGen(ctx, ast.QualifiedName{Module: modName, Name: first.Name()}); err != nil {
		t.Fatalf("describeJavaScriptActionGen: %v", err)
	}
	out := buf.String()

	// Complete body must contain all three sections with content.
	if !strings.Contains(out, "imports $$") {
		t.Errorf("output missing 'imports $$' section")
	}
	if !strings.Contains(out, `import { Big } from "big.js"`) {
		t.Errorf("output missing primary import line")
	}
	if !strings.Contains(out, `import MyType from "./MyType"`) {
		t.Errorf("output missing secondary import line")
	}
	if !strings.Contains(out, "extra $$") {
		t.Errorf("output missing 'extra $$' section")
	}
	if !strings.Contains(out, "function helper() { return 42; }") {
		t.Errorf("output missing extra code content")
	}
	if !strings.Contains(out, "code $$") {
		t.Errorf("output missing 'code $$' section")
	}
	if !strings.Contains(out, "const result = helper();") {
		t.Errorf("output missing user code content")
	}
	if !strings.Contains(out, "return result;") {
		t.Errorf("output missing user code return statement")
	}
	// Verify -- source: comment is present with the source path.
	if !strings.Contains(out, "-- source: javascriptsource") {
		t.Errorf("output missing '-- source:' comment, got:\n%s", out)
	}
	if strings.Contains(out, "NOT FOUND") {
		t.Errorf("output should NOT indicate NOT FOUND when file exists, got:\n%s", out)
	}
}

// TestDescribeJavaScriptActionGen_NoSourceFile shows {} without sections
// and includes a -- source: (NOT FOUND) comment.
func TestDescribeJavaScriptActionGen_NoSourceFile(t *testing.T) {
	w := openMprWriterForTest(t)
	path := w.ConcreteReader().Path()

	be, err := mprbackend.NewFromPath(path)
	if err != nil {
		t.Fatalf("mprbackend.NewFromPath(%s): %v", path, err)
	}
	t.Cleanup(func() { _ = be.Disconnect() })

	ctx := &ExecContext{
		Backend: be,
			MprPath: path,
		JavaActions: mprrepos.NewJavaActionRepository(w), JavaScriptActions: mprrepos.NewJavaScriptActionRepository(w),
		Output: io.Discard,
	}
	ctx.initRoles()
	ctx.ensureCache()

	h, err := getHierarchy(ctx)
	if err != nil {
		t.Fatalf("getHierarchy: %v", err)
	}
	pairs, err := listJavaScriptActionsWithContainerGen(ctx)
	if err != nil {
		t.Fatalf("listJavaScriptActionsWithContainerGen: %v", err)
	}
	if len(pairs) == 0 {
		t.Skip("fixture has no JS actions")
	}
	first := pairs[0].Elem
	modID := h.FindModuleID(modelIDFromElementID(pairs[0].ContainerID))
	modName := h.GetModuleName(modID)

	// Deliberately do NOT create any source file.

	var buf bytes.Buffer
	ctx.Output = &buf
	rebuildDeps(ctx)

	if err := describeJavaScriptActionGen(ctx, ast.QualifiedName{Module: modName, Name: first.Name()}); err != nil {
		t.Fatalf("describeJavaScriptActionGen: %v", err)
	}
	out := buf.String()

	// Body should be just {} with no sections.
	if !strings.Contains(out, "{\n}") {
		t.Errorf("expected body to be just {} when no source file exists, got:\n%s", out)
	}
	if strings.Contains(out, "imports $$") {
		t.Errorf("should NOT contain imports section when no source file")
	}
	if strings.Contains(out, "extra $$") {
		t.Errorf("should NOT contain extra section when no source file")
	}
	if strings.Contains(out, "code $$") {
		t.Errorf("should NOT contain code section when no source file")
	}
	// Must show -- source: (NOT FOUND)
	if !strings.Contains(out, "NOT FOUND") {
		t.Errorf("output must indicate NOT FOUND when source file is absent, got:\n%s", out)
	}
	if !strings.Contains(out, "-- source: javascriptsource") {
		t.Errorf("output missing '-- source:' comment, got:\n%s", out)
	}
}

// TestExecute_ErrorIncludesDuration verifies that when Execute returns an
// error, the error message includes the execution duration.
func TestExecute_ErrorIncludesDuration(t *testing.T) {
	exec := New(io.Discard)
	exec.SetBackend(&mock.MockBackend{
		IsConnectedFunc: func() bool { return true },
	})
	exec.SetQuiet(true)

	// A describe for a nonexistent JS action should produce an error.
	prog, errs := visitor.Build("describe javascript action NonExistentModule.NonExistentAction")
	if len(errs) > 0 {
		t.Fatalf("parse errors: %v", errs)
	}

	for _, stmt := range prog.Statements {
		err := exec.Execute(stmt)
		if err != nil {
			errMsg := err.Error()
			if !strings.Contains(errMsg, "duration:") {
				t.Errorf("error should include 'duration:', got: %q", errMsg)
			}
			return
		}
	}
	t.Skip("no statement produced an error (might need --integration fixture)")
}
