// SPDX-License-Identifier: Apache-2.0

package executor

import (
	"testing"

	"github.com/mendixlabs/mxcli/mdl/ast"
)

// TestMeasureLoopStatementWidthIncludesIteratorSpace verifies that
// measureLoopStatement accounts for IteratorSpace (100px) in addition to
// LoopPadding when calculating loop container width.
//
// Without IteratorSpace, the measured width is 100px smaller than the actual
// BSON size generated by emitLoopedActivityGen. This causes nested loops to
// visually overflow their parent container — the outer loop's box is sized
// too small for the inner loop.
func TestMeasureLoopStatementWidthIncludesIteratorSpace(t *testing.T) {
	m := &layoutMeasurer{}

	// Loop body with 1 activity (width = ActivityWidth = 120)
	stmt := &ast.LoopStmt{
		ListVariable: "L",
		LoopVariable: "I",
		Body: []ast.MicroflowStatement{
			&ast.DeclareStmt{Variable: "X", Type: ast.DataType{Kind: ast.TypeBoolean}},
		},
	}

	bounds := m.measureLoopStatement(stmt)

	// Body width = 120 (1 activity)
	// Expected width = max(120 + 2*50 + 100, 200) = max(320, 200) = 320
	expectedWidth := ActivityWidth + 2*LoopPadding + IteratorSpace
	if bounds.Width != expectedWidth {
		t.Fatalf("measureLoopStatement width = %d, want %d (body=%d + 2*padding=%d + iterator=%d)",
			bounds.Width, expectedWidth, ActivityWidth, 2*LoopPadding, IteratorSpace)
	}

	// Height should account for padding
	expectedHeight := ActivityHeight + 2*LoopPadding
	if bounds.Height < expectedHeight {
		t.Fatalf("measureLoopStatement height = %d, want >= %d",
			bounds.Height, expectedHeight)
	}
}
